name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.17.0"

    - name: Install mkdocs
      run: pip install mkdocs

    - name: Install dependencies
      run: npm install -g clean-css-cli terser

    - name: Build site
      run: mkdocs build

    - name: Validate HTML with W3C validator
      run: |
        wget -q https://github.com/validator/validator/releases/latest/download/vnu.linux.zip
        unzip -q vnu.linux.zip
        
        for file in $(find ./site -name "*.html"); do
          ./vnu-runtime-image/bin/vnu "$file" || true
        done

    - name: Minify JS
      run: |
        for file in site/js/*.js; do
          if [[ "$file" != *.min.js ]]; then
            npx terser "$file" --compress --mangle > "$file.tmp"
            mv "$file.tmp" "$file"
          fi
        done

    - name: Minify CSS
      run: |
        for file in site/css/*.css; do
          if [[ "$file" != *.min.css ]]; then
            cleancss -O1 -o "$file" "$file"
          fi
        done

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./site