name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.17.0"

    - name: Install dependencies
      run: pip install mkdocs mkdocs-material

    - name: Install dependencies
      run: npm ci

    - name: Build site
      run: mkdocs build

    - name: Validate HTML
      uses: Cyb3r-Jak3/html5-validator-action@v1

    - name: Minify JS
      run: npx terser script.js -o script.min.js --compress --mangle

    - name: Minify CSS
      run: npx cssnano style.css style.min.css

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./site